# Generated by Django 3.2.25 on 2024-10-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='body_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
