# Generated by Django 3.2.25 on 2024-10-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0004_testdrive_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive_booking',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
