# Generated by Django 3.2.25 on 2024-10-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0008_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='service',
            field=models.TextField(),
        ),
    ]
