# Generated by Django 3.2.25 on 2024-10-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TC', '0009_alter_product_table_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='details',
            field=models.TextField(),
        ),
    ]
